import { Product } from "@/components/ProductCard";
import product1 from "@/assets/product-1.jpg";
import product2 from "@/assets/product-2.jpg";
import product3 from "@/assets/product-3.jpg";
import product4 from "@/assets/product-4.jpg";

export const products: Product[] = [
  {
    id: "1",
    name: "Dragon Emblem Tee",
    description: "Premium tee with dragon emblem.",
    slug: "dragon-emblem-tee",
    price: 129,
    image: product1,
    images: [product1, product2],
    category: "Signature",
    isNew: true,
    rating: 4.8,
    reviewCount: 234,
    stock: 3,
    specs: { Fabric: "Poly-Cotton 180 GSM", Fit: "Regular", Color: "Black/Gold" },
  },
  {
    id: "2",
    name: "Classic White Premium",
    description: "Classic white premium tee.",
    slug: "classic-white-premium",
    price: 99,
    image: product2,
    images: [product2, product1],
    category: "Essential",
    rating: 4.6,
    reviewCount: 156,
    discount: 20,
    stock: 12,
    specs: { Fabric: "Cotton", Fit: "Slim", Color: "White" },
  },
  {
    id: "3",
    name: "Charcoal Elite",
    description: "Charcoal elite edition tee.",
    slug: "charcoal-elite",
    price: 119,
    image: product3,
    images: [product3, product4],
    category: "Essential",
    isNew: true,
    rating: 4.9,
    reviewCount: 189,
    stock: 0,
    specs: { Fabric: "Polyester", Fit: "Athletic", Color: "Charcoal" },
  },
  {
    id: "4",
    name: "Navy Gold Edition",
    description: "Navy gold edition tee.",
    slug: "navy-gold-edition",
    price: 139,
    image: product4,
    images: [product4, product3],
    category: "Limited",
    rating: 5.0,
    reviewCount: 98,
    stock: 5,
    specs: { Fabric: "Poly-Cotton", Fit: "Regular", Color: "Navy/Gold" },
  },
  {
    id: "5",
    name: "Phoenix Rise Tee",
    description: "Phoenix rise signature tee.",
    slug: "phoenix-rise-tee",
    price: 129,
    image: product1,
    images: [product1, product2],
    category: "Signature",
    rating: 4.7,
    reviewCount: 167,
    discount: 15,
    stock: 9,
    specs: { Fabric: "Cotton", Fit: "Regular", Color: "Red/Gold" },
  },
  {
    id: "6",
    name: "Midnight Black Pro",
    description: "Midnight black pro essential tee.",
    slug: "midnight-black-pro",
    price: 109,
    image: product3,
    images: [product3, product1],
    category: "Essential",
    rating: 4.5,
    reviewCount: 143,
    stock: 20,
    specs: { Fabric: "Cotton", Fit: "Regular", Color: "Black" },
  },
];

export const getProductById = (id: string) => products.find((p) => p.id === id);

